### ISSUE TITLE
기사미 시세미 연동 (Merge 리팩토링)

### ISSUE THREAD

**Issue by ghkvud2** [tuguri8/gisame#11]
### 통합전 패키지 (AS-IS)
1) me.gisa.api.naver
2) me.gisa.api.daum
3) me.gisa.api.rss

### 통합후 패키지 (TO-BE)
1) me.gisa.api.controller
2) me.gisa.api.service
3) me.gisa.api.repository
4) me.gisa.api.datatool
 - naver
 - daum
 - rss
 - siseme

### 명명규칙
1) API 호출시 응답받는 model 명은 <b>버전+도메인+Response</b>로 통일합니다.
 - V1NaverNewsResponse
 - V1DaumNewsResponse
 - V1RssNewsResponse

---
# me.gisa.api.service.news 패키지
- 시세미에서 받아온 지역명을 기준으로 뉴스 API를 호출해서 DB에 저장하는 서비스 로직 구현
- 중복되는 데이터없이 DB에 저장

## 인터페이스명
- NewsService
## 인터페이스 구현체
- NaverNewsServiceImpl (이화평 구현)
- DaumNewsServiceImpl (승우님 구현)
- GoogleNewsServiceImpl (유하님 구현)
---
# me.gisa.api.controller 패키지
- 클라이언트(시세미 서버)로부터 들어온 요청을 처리하는 컨트롤러
- 저장된 DB내의 뉴스 목록에서 파라미터에 따라 뉴스를 가져와서 반환한다.

## 컨트롤러명
- NewsController

## 요청 URL
 - 뉴스 목록 요청 
 - 파라미터 Default 값 등은 합의 필요

1) 날짜 (startDate / endDate)
 - v1/news/list?startDate=20190701&endDate=20190725

2) 지역 코드 
 - v1/news/list?regionCode=11

3) 검색 키워드
 - v1/news/list?searchKeyword=전세

4) 뉴스 타입 (naver, daum, google)
 - v1/news/list?newsType=naver

5) 페이징 처리
 - v1/news/list?page=1&size=10
---
# me.gisa.api.service.gisame패키지 (공통 부분)
- DB에 저장된 뉴스정보를 전달된 파라미터(파라미터 목록 참고)를 기준으로 Select하여 반환
## 인터페이스명
- GisameService
## 인터페이스 구현체
- GisameServiceImpl
## 반환형
- NewsModel 클래스 형태로 반환

---

# 파라미터 목록

   | 파라미터      | 내용                            |
   | ------------- | ------------------------------- |
   | startDate     | 시작 날짜(YYYYMMDD)             |
   | endDate       | 종료 날짜(YYYYMMDD)             |
   | regionCode    | 지역 코드                       |
   | searchKeyword | 검색 키워드(부동산, 전세, 월세) |
   | newsType      | 뉴스 타입(naver,daum)           |
   | page          | 페이지 번호                     |
   | size          | 페이지 당 뉴스 개수             |

**Comment by tuguri8** [comment]
RegionGroup Enum에서 "세종특별자치시" -> "세종특별시" 라고 고쳐야 오류 안나요!!
